一致するリソースがない場合、404 Not Found  を返却する
kazuki43zoo/api-stub pull request #56
Opened 2017-04-06 14:52 UTC by arakists

2017-04-06 14:55 UTC, kazuki43zoo commented
PRの内容と直接関係ないdiffがでているので、rebaseしてから再度PRしてほしいです。

2017-04-06 14:56 UTC, kazuki43zoo commented
ってか、PR先のbranchが間違っている説。

2017-04-06 15:16 UTC, kazuki43zoo commented on api-stub-core/src/main/java/com/kazuki43zoo/api/ApiStubRestController.java
> +        if (Objects.isNull(api)) {
API情報の登録は任意なので、API定義なし＝404 Not Foundというのは設計思想と一致しません。
おそらく、やりたいことはレスポンスデータが未登録だった時のデフォルト動作を404 Not Foundにしたい！ということだと思うので、`MockResponseHandler#perform`の・・・

```
if (apiResponse.getId() == 0) {
    evidence.warn("Mock Response is not found.");
    // このあたりを修正
} else {
    evidence.info("Mock Response is {}.", apiResponse.getId());
}
```

あたりを修正するのが妥当な気がします。
＋
データが見つからない時のデフォルト動作を指定（カスタマイズ）するためのプロパティを用意してほしいです。デフォルトはニーズが高そうな404でOK。

よろしくお願いします。

2017-04-07 01:55 UTC, arakists commented on api-stub-core/src/main/java/com/kazuki43zoo/api/ApiStubRestController.java
> +        if (Objects.isNull(api)) {
> API情報の登録は任意なので、API定義なし＝404 Not Foundというのは設計思想と一致しません。
上記は理解しました。
ただ、登録したデータにマッチしない場合、正常の 200 が返却され、レスポンスボディが空だとデータの設定ミスなのか、リクエストデータのミスかわからなくなるかと思いました。

であれば、ログをINFOとかで出力するのはどうでしょうか？

2017-04-07 01:58 UTC, arakists commented
> ってか、PR先のbranchが間違っている説。

しれっとmaster　に変えておきました。
いつものgit flow の癖で・・

2017-04-07 02:03 UTC, arakists commented on api-stub-core/src/main/java/com/kazuki43zoo/api/ApiStubRestController.java
> +        if (Objects.isNull(api)) {
> おそらく、やりたいことはレスポンスデータが未登録だった時のデフォルト動作を404 Not Foundにしたい！ということだと思うので、MockResponseHandler#performの・・・

了解です。対応してみます

2017-04-09 12:26 UTC, arakists commented
Mockレスポンスが見つからない場合、404(デフォルト) を返却するように変更してました。

`application-api-stub.property` にプロパティを追加しています。
役割的に、ここに追加するのがいいのか・・・

2017-04-09 15:56 UTC, kazuki43zoo requested changes
@arakists 

いくつかコメントしました。

2017-04-09 15:56 UTC, kazuki43zoo commented on api-stub-core/src/main/java/com/kazuki43zoo/api/ApiStubRestController.java
> +            log.info("not match the request data. Path:{} Method:{}", path, method);
ここでログ出す必要性ありますか？ API定義の登録は任意なので、登録してないとその度のINFOログがでるのはうざいと思うのですが・・。

2017-04-09 15:56 UTC, kazuki43zoo commented on api-stub-core/src/main/java/com/kazuki43zoo/api/handler/MockResponseHandler.java
> +    @Value("${mockresponse.notfound.return.error}")
`@Value`じゃなくて、[Type-safe Configuration Properties](http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties)の仕組みを使いようにしてほしいです。すでに`ApiStubProperties`というクラスがあるので、そのクラスにプロパティを追加する形にしてほしい。

2017-04-09 15:56 UTC, kazuki43zoo commented on api-stub-core/src/main/java/com/kazuki43zoo/api/handler/MockResponseHandler.java
> +            if (isErrorResponse) {
すぐにreturnするのではなく、データがない時のステータスコードを決定するようにし、後続処理は従来通り流すようにしてほしいです。

2017-04-09 15:56 UTC, kazuki43zoo commented on api-stub-core/src/main/resources/application-api-stub.properties
> +# Mock Response Data Setting
定義するなら・・・api-stub-appのapplication.propertiesですね。

2017-04-14 14:13 UTC, arakists commented on api-stub-core/src/main/java/com/kazuki43zoo/api/ApiStubRestController.java
> +            log.info("not match the request data. Path:{} Method:{}", path, method);
なんだかんだ利用する側としては、合致しない場合の解析したい場合、
ログは必要かなあと思いました。

Debug で出力するように変更しました。

2017-04-14 14:14 UTC, arakists commented
レビューコメントに一通り対応してみました。
確認お願いします。

2017-07-19 18:27 UTC, kazuki43zoo commented
Thanks for your contribution !

I've polished and merged via 3bb902071a2ce76da388689fd0154445df3908d0

2017-07-19 18:27 UTC, closed without merging